const whoami = {
	meta: {
		executionTime: 0.206,
		status_code: 200,
		code: 200,
		requestId: '4401853a-9f3c-46dd-943a-8f84827190b7-WM-LGA',
		responseTime: 0.206,
		statusCode: 200,
		timestamp: 1501802966,
		execution_time: 0.206,
	},
	result: {
		warnings: null,
		errors: null,
		pagination: null,
		payload: [{
			settingsDimensions: {
				base: 'wm',
				business: 'tech-services',
				company: 'company1',
				department: 'defaultOrgUnit',
				user: 'userUuid',
				special: null,
				override: null,
			},
			entityConfigurations: [],
			mainNav: {
				children: [{
					children: null,
					action: {
						uuid: 'be0a4cea-ebc6-4f07-b375-4f8bce5be26f',
						createdOn: null,
						updatedOn: null,
						deletedOn: null,
						description: 'SkyNet Home',
						worktronFunctionType: 'ROUTE',
						type: 'ROUTE',
						name: 'visit',
						args: '/',
						implementation: null,
					},
					label: 'Home',
					icon: null,
				}, {
					children: null,
					action: {
						uuid: 'd148f7e2-0c41-4684-90fa-c5b395fbd155',
						createdOn: null,
						updatedOn: null,
						deletedOn: null,
						description: 'Payments Home',
						worktronFunctionType: 'ROUTE',
						type: 'ROUTE',
						name: 'visit',
						args: '/payments',
						implementation: null,
					},
					label: 'Payments',
					icon: null,
				}],
				action: null,
				label: null,
				icon: null,
			},
			userNav: {
				children: [{
					children: null,
					action: {
						uuid: 'be0a4cea-ebc6-4f07-b375-4f8bce5be26f',
						createdOn: null,
						updatedOn: null,
						deletedOn: null,
						description: 'SkyNet Home',
						worktronFunctionType: 'ROUTE',
						type: 'ROUTE',
						name: 'visit',
						args: '/',
						implementation: null,
					},
					label: 'Profile',
					icon: null,
				}, {
					children: null,
					action: {
						uuid: 'd148f7e2-0c41-4684-90fa-c5b395fbd155',
						createdOn: null,
						updatedOn: null,
						deletedOn: null,
						description: 'Payments Home',
						worktronFunctionType: 'ROUTE',
						type: 'ROUTE',
						name: 'visit',
						args: '/payments',
						implementation: null,
					},
					label: 'Settings',
					icon: null,
				}],
				action: null,
				label: null,
				icon: null,
			},
			footerNav: {
				children: null,
				action: null,
				label: 'Footer Nav',
				icon: null,
			},
			apiOrgUnits: [{
				uuid: 'a3840ff5-f819-415d-b790-95069999f221',
				createdOn: null,
				updatedOn: null,
				deletedOn: null,
				name: 'Default Org Unit',
				description: "The only org unit you'll ever need",
				parentUuid: null,
				order: 1,
				costCenterUuid: null,
				memberCount: 1,
				members: ['userUuid1'],
				children: null,
				orgChartUuid: '3bb8e158-6360-4512-9b3a-d3903e14f210',
			}],
			selectedApiOrgUnit: {
				uuid: 'a3840ff5-f819-415d-b790-95069999f221',
				createdOn: null,
				updatedOn: null,
				deletedOn: null,
				name: 'Default Org Unit',
				description: "The only org unit you'll ever need",
				parentUuid: null,
				order: 1,
				costCenterUuid: null,
				memberCount: 1,
				members: ['userUuid1'],
				children: null,
				orgChartUuid: '3bb8e158-6360-4512-9b3a-d3903e14f210',
			},
			locale: 'en_US',
			currency: {
				uuid: 'currencyUuid1',
				createdOn: null,
				updatedOn: null,
				deletedOn: null,
				code: 'USD',
				displayName: 'US Dollars',
			},
			actionHistory: [],
			notifications: [{
				name: 'wake-up',
				description: 'Time to make the donuts!',
				actions: null,
			}],
			welcomeAction: {
				uuid: 'be0a4cea-ebc6-4f07-b375-4f8bce5be26f',
				createdOn: null,
				updatedOn: null,
				deletedOn: null,
				description: 'SkyNet Home',
				worktronFunctionType: 'ROUTE',
				type: 'ROUTE',
				name: 'visit',
				args: '/',
				implementation: null,
			},
			logo: {
				name: 'wmLogo',
				description: 'WorkMarket',
				base64: 'base64',
			},
			avatar: {
				name: 'userAvatar',
				description: 'UserTron',
				base64: 'base64',
			},
		}],
	},
};

export default whoami;
